// 100-word sample set. Each entry: { word, meaning, exampleEn, exampleKo }.
// `word` must be lowercase, exactly 5 letters, and present in dictionary.js.
// Replace or extend later — the game picks one per day based on START_DATE in script.js.
const WORDS = [
  { word: "apple", meaning: "사과", exampleEn: "I ate an apple for breakfast.", exampleKo: "나는 아침으로 사과를 먹었다." },
  { word: "beach", meaning: "해변", exampleEn: "We walked along the beach at sunset.", exampleKo: "우리는 해질녘에 해변을 따라 걸었다." },
  { word: "chair", meaning: "의자", exampleEn: "Please pull up a chair and sit.", exampleKo: "의자를 끌어와 앉으세요." },
  { word: "dance", meaning: "춤, 춤추다", exampleEn: "They love to dance at weddings.", exampleKo: "그들은 결혼식에서 춤추는 걸 좋아한다." },
  { word: "eagle", meaning: "독수리", exampleEn: "An eagle soared above the mountain.", exampleKo: "독수리가 산 위로 날아올랐다." },
  { word: "flame", meaning: "불꽃", exampleEn: "The candle flame flickered in the wind.", exampleKo: "촛불의 불꽃이 바람에 흔들렸다." },
  { word: "grape", meaning: "포도", exampleEn: "She picked a bunch of grapes.", exampleKo: "그녀는 포도 한 송이를 땄다." },
  { word: "heart", meaning: "심장, 마음", exampleEn: "His heart raced before the speech.", exampleKo: "그는 연설 전에 심장이 두근거렸다." },
  { word: "image", meaning: "이미지, 상", exampleEn: "The image on the screen was clear and sharp.", exampleKo: "화면 속 이미지는 선명하고 또렷했다." },
  { word: "juice", meaning: "주스", exampleEn: "I drink orange juice every morning.", exampleKo: "나는 매일 아침 오렌지 주스를 마신다." },
  { word: "knife", meaning: "칼", exampleEn: "Use a sharp knife to cut the bread.", exampleKo: "빵을 자를 때 날카로운 칼을 쓰세요." },
  { word: "lemon", meaning: "레몬", exampleEn: "Add a slice of lemon to your tea.", exampleKo: "차에 레몬 한 조각을 넣으세요." },
  { word: "mango", meaning: "망고", exampleEn: "The mango was perfectly ripe.", exampleKo: "망고가 완벽하게 익었다." },
  { word: "night", meaning: "밤", exampleEn: "The stars shine bright at night.", exampleKo: "밤에 별들이 밝게 빛난다." },
  { word: "ocean", meaning: "바다", exampleEn: "The ocean stretched to the horizon.", exampleKo: "바다가 수평선까지 펼쳐졌다." },
  { word: "peach", meaning: "복숭아", exampleEn: "She picked a juicy peach from the tree.", exampleKo: "그녀는 나무에서 즙 많은 복숭아를 땄다." },
  { word: "queen", meaning: "여왕", exampleEn: "The queen waved from the balcony.", exampleKo: "여왕이 발코니에서 손을 흔들었다." },
  { word: "river", meaning: "강", exampleEn: "We swam across the river.", exampleKo: "우리는 강을 헤엄쳐 건넜다." },
  { word: "snake", meaning: "뱀", exampleEn: "A small snake slithered through the grass.", exampleKo: "작은 뱀이 풀밭을 미끄러져 갔다." },
  { word: "table", meaning: "탁자, 식탁", exampleEn: "Set the table for dinner.", exampleKo: "저녁 식사를 위해 식탁을 차려요." },
  { word: "voice", meaning: "목소리", exampleEn: "Her voice was calm and clear.", exampleKo: "그녀의 목소리는 차분하고 또렷했다." },
  { word: "water", meaning: "물", exampleEn: "Drink plenty of water every day.", exampleKo: "매일 물을 충분히 마셔요." },
  { word: "youth", meaning: "젊음, 청춘", exampleEn: "He spent his youth traveling abroad.", exampleKo: "그는 젊은 시절을 해외 여행으로 보냈다." },
  { word: "zebra", meaning: "얼룩말", exampleEn: "The zebra has black and white stripes.", exampleKo: "얼룩말은 검고 흰 줄무늬가 있다." },
  { word: "brave", meaning: "용감한", exampleEn: "She was brave enough to speak up.", exampleKo: "그녀는 용감하게 말할 수 있었다." },
  { word: "cloud", meaning: "구름", exampleEn: "A single cloud drifted in the sky.", exampleKo: "구름 하나가 하늘에 떠다녔다." },
  { word: "drink", meaning: "음료, 마시다", exampleEn: "Let's get a drink after work.", exampleKo: "퇴근 후에 한잔하러 가자." },
  { word: "elbow", meaning: "팔꿈치", exampleEn: "He hit his elbow on the door.", exampleKo: "그는 팔꿈치를 문에 부딪쳤다." },
  { word: "fault", meaning: "잘못, 결함", exampleEn: "It's not your fault.", exampleKo: "그건 네 잘못이 아니야." },
  { word: "ghost", meaning: "유령", exampleEn: "The old house is said to have a ghost.", exampleKo: "그 오래된 집에는 유령이 있다고 한다." },
  { word: "horse", meaning: "말", exampleEn: "The horse galloped across the field.", exampleKo: "말이 들판을 가로질러 달렸다." },
  { word: "ivory", meaning: "상아", exampleEn: "The piano keys were made of ivory.", exampleKo: "피아노 건반은 상아로 만들어졌다." },
  { word: "jelly", meaning: "젤리, 잼", exampleEn: "He spread jelly on his toast.", exampleKo: "그는 토스트에 잼을 발랐다." },
  { word: "knock", meaning: "노크하다, 두드리다", exampleEn: "Please knock before you enter.", exampleKo: "들어오기 전에 노크해 주세요." },
  { word: "light", meaning: "빛", exampleEn: "Turn on the light, please.", exampleKo: "불 좀 켜 주세요." },
  { word: "money", meaning: "돈", exampleEn: "He saved money for a new car.", exampleKo: "그는 새 차를 사려고 돈을 모았다." },
  { word: "north", meaning: "북쪽", exampleEn: "Geese fly north in spring.", exampleKo: "기러기는 봄에 북쪽으로 날아간다." },
  { word: "olive", meaning: "올리브", exampleEn: "She added olives to the salad.", exampleKo: "그녀는 샐러드에 올리브를 넣었다." },
  { word: "plant", meaning: "식물, 심다", exampleEn: "I water this plant every morning.", exampleKo: "나는 매일 아침 이 식물에 물을 준다." },
  { word: "quiet", meaning: "조용한", exampleEn: "The library was very quiet.", exampleKo: "도서관은 매우 조용했다." },
  { word: "rapid", meaning: "빠른", exampleEn: "There was a rapid change in weather.", exampleKo: "날씨가 빠르게 변했다." },
  { word: "sweet", meaning: "달콤한", exampleEn: "These strawberries are very sweet.", exampleKo: "이 딸기들은 매우 달다." },
  { word: "train", meaning: "기차", exampleEn: "We took the train to Busan.", exampleKo: "우리는 부산까지 기차를 탔다." },
  { word: "vault", meaning: "금고", exampleEn: "The bank vault was locked tight.", exampleKo: "은행 금고는 단단히 잠겨 있었다." },
  { word: "whale", meaning: "고래", exampleEn: "A whale surfaced near the boat.", exampleKo: "고래 한 마리가 배 근처에서 떠올랐다." },
  { word: "yacht", meaning: "요트", exampleEn: "They sailed the yacht around the bay.", exampleKo: "그들은 만을 따라 요트를 몰았다." },
  { word: "angel", meaning: "천사", exampleEn: "She has the voice of an angel.", exampleKo: "그녀는 천사 같은 목소리를 가졌다." },
  { word: "bread", meaning: "빵", exampleEn: "I baked fresh bread this morning.", exampleKo: "나는 오늘 아침에 갓 구운 빵을 만들었다." },
  { word: "child", meaning: "아이", exampleEn: "The child laughed with joy.", exampleKo: "아이가 기뻐서 웃었다." },
  { word: "dream", meaning: "꿈", exampleEn: "I had a strange dream last night.", exampleKo: "어젯밤 이상한 꿈을 꾸었다." },
  { word: "earth", meaning: "지구, 흙", exampleEn: "The earth orbits the sun.", exampleKo: "지구는 태양 주위를 돈다." },
  { word: "fresh", meaning: "신선한", exampleEn: "This fish is very fresh.", exampleKo: "이 생선은 매우 신선하다." },
  { word: "glass", meaning: "유리, 잔", exampleEn: "Pour me a glass of water.", exampleKo: "물 한 잔만 따라 주세요." },
  { word: "happy", meaning: "행복한", exampleEn: "She felt happy on her birthday.", exampleKo: "그녀는 생일에 행복했다." },
  { word: "input", meaning: "입력, 의견", exampleEn: "Please give me your input on this idea.", exampleKo: "이 아이디어에 대한 의견을 주세요." },
  { word: "jewel", meaning: "보석", exampleEn: "The ring had a sparkling jewel.", exampleKo: "반지에 반짝이는 보석이 박혀 있었다." },
  { word: "kayak", meaning: "카약", exampleEn: "We rented a kayak for the afternoon.", exampleKo: "우리는 오후 동안 카약을 빌렸다." },
  { word: "learn", meaning: "배우다", exampleEn: "I want to learn Spanish.", exampleKo: "나는 스페인어를 배우고 싶다." },
  { word: "music", meaning: "음악", exampleEn: "She listens to music while studying.", exampleKo: "그녀는 공부하면서 음악을 듣는다." },
  { word: "novel", meaning: "소설", exampleEn: "He finished reading the novel in one day.", exampleKo: "그는 하루 만에 소설을 다 읽었다." },
  { word: "opera", meaning: "오페라", exampleEn: "We watched an opera in Vienna.", exampleKo: "우리는 빈에서 오페라를 봤다." },
  { word: "paint", meaning: "페인트, 그리다", exampleEn: "She wants to paint a landscape.", exampleKo: "그녀는 풍경을 그리고 싶어 한다." },
  { word: "quilt", meaning: "누비이불", exampleEn: "Grandma made a warm quilt.", exampleKo: "할머니는 따뜻한 누비이불을 만들어 주셨다." },
  { word: "radio", meaning: "라디오", exampleEn: "He listens to the radio every morning.", exampleKo: "그는 매일 아침 라디오를 듣는다." },
  { word: "smile", meaning: "미소", exampleEn: "Her smile brightened the room.", exampleKo: "그녀의 미소가 방을 밝혔다." },
  { word: "truth", meaning: "진실", exampleEn: "Tell me the truth.", exampleKo: "사실대로 말해 주세요." },
  { word: "urban", meaning: "도시의", exampleEn: "He prefers urban life to the countryside.", exampleKo: "그는 시골보다 도시 생활을 더 좋아한다." },
  { word: "vivid", meaning: "생생한", exampleEn: "I had a vivid dream last night.", exampleKo: "어젯밤 생생한 꿈을 꾸었다." },
  { word: "world", meaning: "세계", exampleEn: "She traveled around the world.", exampleKo: "그녀는 세계를 일주했다." },
  { word: "young", meaning: "젊은", exampleEn: "He's still young and full of energy.", exampleKo: "그는 아직 젊고 에너지가 넘친다." },
  { word: "beast", meaning: "짐승", exampleEn: "The beast roared in the forest.", exampleKo: "짐승이 숲속에서 으르렁거렸다." },
  { word: "crisp", meaning: "바삭한", exampleEn: "The toast was perfectly crisp.", exampleKo: "토스트가 완벽하게 바삭했다." },
  { word: "dwarf", meaning: "난쟁이", exampleEn: "A friendly dwarf greeted the travelers.", exampleKo: "친절한 난쟁이가 여행자들을 맞이했다." },
  { word: "eight", meaning: "여덟", exampleEn: "She has eight pieces of candy.", exampleKo: "그녀는 사탕 여덟 개를 가지고 있다." },
  { word: "field", meaning: "들판", exampleEn: "The field was full of yellow flowers.", exampleKo: "들판은 노란 꽃들로 가득했다." },
  { word: "grain", meaning: "곡물, 알갱이", exampleEn: "Rice is the main grain in Asia.", exampleKo: "쌀은 아시아의 주요 곡물이다." },
  { word: "honey", meaning: "꿀", exampleEn: "Add a spoon of honey to your tea.", exampleKo: "차에 꿀 한 숟갈을 넣으세요." },
  { word: "irony", meaning: "아이러니, 역설", exampleEn: "The irony was not lost on him.", exampleKo: "그는 그 아이러니를 놓치지 않았다." },
  { word: "joker", meaning: "농담꾼, 조커", exampleEn: "He's always the joker in the group.", exampleKo: "그는 항상 우리 무리의 농담꾼이다." },
  { word: "level", meaning: "수준, 단계", exampleEn: "Her English is at an advanced level.", exampleKo: "그녀의 영어 실력은 고급 수준이다." },
  { word: "march", meaning: "행진하다, 3월", exampleEn: "The soldiers marched through town.", exampleKo: "군인들이 마을을 행진해 지나갔다." },
  { word: "pride", meaning: "자부심", exampleEn: "She felt great pride in her work.", exampleKo: "그녀는 자신의 일에 큰 자부심을 느꼈다." },
  { word: "quest", meaning: "탐구, 모험", exampleEn: "The hero began his quest at dawn.", exampleKo: "영웅은 새벽에 모험을 시작했다." },
  { word: "robot", meaning: "로봇", exampleEn: "The robot vacuumed the floor.", exampleKo: "로봇이 바닥을 청소했다." },
  { word: "storm", meaning: "폭풍", exampleEn: "A storm is coming tonight.", exampleKo: "오늘 밤 폭풍이 온다." },
  { word: "theft", meaning: "절도", exampleEn: "The theft was reported to the police.", exampleKo: "절도 사건이 경찰에 신고됐다." },
  { word: "under", meaning: "~아래", exampleEn: "The cat is under the table.", exampleKo: "고양이가 식탁 아래에 있다." },
  { word: "value", meaning: "가치", exampleEn: "Family is of great value to him.", exampleKo: "그에게 가족은 큰 가치를 지닌다." },
  { word: "witch", meaning: "마녀", exampleEn: "The witch lived deep in the forest.", exampleKo: "마녀는 숲속 깊은 곳에 살았다." },
  { word: "yield", meaning: "양보하다, 산출하다", exampleEn: "Drivers must yield at the intersection.", exampleKo: "운전자는 교차로에서 양보해야 한다." },
  { word: "alert", meaning: "경계하는, 기민한", exampleEn: "Stay alert while crossing the street.", exampleKo: "길을 건널 때 경계하세요." },
  { word: "blink", meaning: "깜박이다", exampleEn: "Don't blink or you'll miss it.", exampleKo: "눈을 깜박이면 놓칠 거예요." },
  { word: "candy", meaning: "사탕", exampleEn: "The kids ate too much candy.", exampleKo: "아이들이 사탕을 너무 많이 먹었다." },
  { word: "debit", meaning: "출금, 체크카드", exampleEn: "Pay with a debit card.", exampleKo: "체크카드로 결제하세요." },
  { word: "enjoy", meaning: "즐기다", exampleEn: "I enjoy walking in the park.", exampleKo: "나는 공원에서 걷는 것을 즐긴다." },
  { word: "frost", meaning: "서리", exampleEn: "There was frost on the window.", exampleKo: "창문에 서리가 끼었다." },
  { word: "giant", meaning: "거대한, 거인", exampleEn: "A giant tree stood in the yard.", exampleKo: "거대한 나무가 마당에 서 있었다." },
  { word: "hotel", meaning: "호텔", exampleEn: "We stayed at a small hotel by the sea.", exampleKo: "우리는 바닷가의 작은 호텔에 묵었다." },
  { word: "index", meaning: "색인, 지수", exampleEn: "Check the index at the back of the book.", exampleKo: "책 뒤쪽의 색인을 확인하세요." },
  { word: "lucky", meaning: "운이 좋은", exampleEn: "You're lucky to have such good friends.", exampleKo: "이렇게 좋은 친구들이 있어서 운이 좋다." }
];
